class LoadRsvPdata < ActiveRecord::Migration
  def change
  	u1 = Rsvp.new(:first_name => 'Michael', :last_name => 'Li', :confirmation_code =>'MOMANDDAD')
    u1.save(:validate => false)
u2 = Rsvp.new(:first_name => 'Ruey', :last_name => 'Li', :confirmation_code =>'MOMANDDAD')
    u2.save(:validate => false)
u3 = Rsvp.new(:first_name => 'Amy', :last_name => 'Li', :confirmation_code =>'RUBYRELAXER')
    u3.save(:validate => false)
u4 = Rsvp.new(:first_name => 'Eric', :last_name => 'Tamura', :confirmation_code =>'RUBYRELAXER')
    u4.save(:validate => false)
u5 = Rsvp.new(:first_name => 'Emily', :last_name => 'Li', :confirmation_code =>'AUNTEMILY')
    u5.save(:validate => false)
u8 = Rsvp.new(:first_name => 'David', :last_name => 'Li', :confirmation_code =>'NEXTUP')
    u8.save(:validate => false)
u9 = Rsvp.new(:first_name => 'Justina', :last_name => 'Chen', :confirmation_code =>'NEXTUP')
    u9.save(:validate => false)
u10 = Rsvp.new(:first_name => 'Michael', :last_name => 'Lin', :confirmation_code =>'ENLOE')
    u10.save(:validate => false)
u11 = Rsvp.new(:first_name => 'Willson', :last_name => 'Mock', :confirmation_code =>'SON')
    u11.save(:validate => false)
u12 = Rsvp.new(:first_name => 'Edwin', :last_name => 'Sam', :confirmation_code =>'TSWIZZLE')
    u12.save(:validate => false)
u13 = Rsvp.new(:first_name => 'Ed', :last_name => 'Pak', :confirmation_code =>'PAKMAN')
    u13.save(:validate => false)
u14 = Rsvp.new(:first_name => 'Joe', :last_name => 'Chang', :confirmation_code =>'COOP')
    u14.save(:validate => false)
u15 = Rsvp.new(:first_name => 'Richard', :last_name => 'Yan', :confirmation_code =>'WIFEY')
    u15.save(:validate => false)
u16 = Rsvp.new(:first_name => 'Jennifer', :last_name => 'Yan', :confirmation_code =>'WIFEY')
    u16.save(:validate => false)
u17 = Rsvp.new(:first_name => 'Angelina', :last_name => 'Ang', :confirmation_code =>'ORIE-O')
    u17.save(:validate => false)
u18 = Rsvp.new(:first_name => 'Nick', :last_name => 'Nieh', :confirmation_code =>'')
    u18.save(:validate => false)
u19 = Rsvp.new(:first_name => 'Harrison', :last_name => 'McCreary', :confirmation_code =>'YOSHI')
    u19.save(:validate => false)
u20 = Rsvp.new(:first_name => 'Adal', :last_name => 'Tecleab', :confirmation_code =>'ERITREANSHOCKER')
    u20.save(:validate => false)
u21 = Rsvp.new(:first_name => 'Lauren', :last_name => 'Muller', :confirmation_code =>'ERITREANSHOCKER')
    u21.save(:validate => false)
u22 = Rsvp.new(:first_name => 'Grant', :last_name => 'Corley', :confirmation_code =>'WILDERNESSREFLECTIONS')
    u22.save(:validate => false)
u23 = Rsvp.new(:first_name => 'Jon', :last_name => 'Stockton', :confirmation_code =>'')
    u23.save(:validate => false)
u24 = Rsvp.new(:first_name => 'Emily', :last_name => 'Dieker', :confirmation_code =>'')
    u24.save(:validate => false)
u25 = Rsvp.new(:first_name => 'Amber', :last_name => 'Persyn', :confirmation_code =>'FLORALCITY')
    u25.save(:validate => false)
u26 = Rsvp.new(:first_name => 'Harvey', :last_name => 'Persyn', :confirmation_code =>'FLORALCITY')
    u26.save(:validate => false)
u27 = Rsvp.new(:first_name => 'Stephen', :last_name => 'Li', :confirmation_code =>'PORTILLOS')
    u27.save(:validate => false)
u28 = Rsvp.new(:first_name => 'Chris', :last_name => 'Wargo', :confirmation_code =>'PORTILLOS')
    u28.save(:validate => false)
u29 = Rsvp.new(:first_name => 'Jonathon', :last_name => 'Li', :confirmation_code =>'')
    u29.save(:validate => false)
u30 = Rsvp.new(:first_name => 'Michael', :last_name => 'Hsu', :confirmation_code =>'HSUPERMAN')
    u30.save(:validate => false)
u31 = Rsvp.new(:first_name => 'Michelle', :last_name => 'Lin', :confirmation_code =>'HSUPERMAN')
    u31.save(:validate => false)
u32 = Rsvp.new(:first_name => 'Alan', :last_name => 'Lin', :confirmation_code =>'LILAOSHI')
    u32.save(:validate => false)
u33 = Rsvp.new(:first_name => 'Jean', :last_name => 'Lin', :confirmation_code =>'LILAOSHI')
    u33.save(:validate => false)
u34 = Rsvp.new(:first_name => 'Kenny', :last_name => 'Lui', :confirmation_code =>'GO-FISH')
    u34.save(:validate => false)
u35 = Rsvp.new(:first_name => 'Lan', :last_name => 'Zhu', :confirmation_code =>'GO-FISH')
    u35.save(:validate => false)
u36 = Rsvp.new(:first_name => 'Jessica', :last_name => 'Lee', :confirmation_code =>'HIGHRISE5')
    u36.save(:validate => false)
u37 = Rsvp.new(:first_name => 'Johnny', :last_name => 'Shieh', :confirmation_code =>'KANGAROO')
    u37.save(:validate => false)
u38 = Rsvp.new(:first_name => 'David', :last_name => 'Chu', :confirmation_code =>'DRDAVE')
    u38.save(:validate => false)
u39 = Rsvp.new(:first_name => 'Christina', :last_name => 'Lee', :confirmation_code =>'DRDAVE')
    u39.save(:validate => false)
u40 = Rsvp.new(:first_name => 'Andrew', :last_name => 'Pendray', :confirmation_code =>'KEIZER')
    u40.save(:validate => false)
u41 = Rsvp.new(:first_name => 'Krystal', :last_name => 'Wang', :confirmation_code =>'KEIZER')
    u41.save(:validate => false)
u42 = Rsvp.new(:first_name => 'James', :last_name => 'Nguyen', :confirmation_code =>'NITROGEN')
    u42.save(:validate => false)
u43 = Rsvp.new(:first_name => 'Leslie', :last_name => 'Tou', :confirmation_code =>'LTSTAR16')
    u43.save(:validate => false)
u44 = Rsvp.new(:first_name => 'Adam', :last_name => 'Wolfe', :confirmation_code =>'LTSTAR16')
    u44.save(:validate => false)
u45 = Rsvp.new(:first_name => 'Alice', :last_name => 'Hsu', :confirmation_code =>'MATCHMAKER')
    u45.save(:validate => false)
u46 = Rsvp.new(:first_name => 'Sean', :last_name => 'Gee', :confirmation_code =>'MATCHMAKER')
    u46.save(:validate => false)
u47 = Rsvp.new(:first_name => 'Stephanie', :last_name => 'Chiu', :confirmation_code =>'DOOKIES')
    u47.save(:validate => false)
u48 = Rsvp.new(:first_name => 'Josephine', :last_name => 'Liu', :confirmation_code =>'MATHLETES')
    u48.save(:validate => false)
u49 = Rsvp.new(:first_name => 'David', :last_name => 'Gironda', :confirmation_code =>'BMO')
    u49.save(:validate => false)
u50 = Rsvp.new(:first_name => 'Valerie', :last_name => 'Liu', :confirmation_code =>'BMO')
    u50.save(:validate => false)
u51 = Rsvp.new(:first_name => 'Richard', :last_name => 'Liu', :confirmation_code =>'MATHLETES')
    u51.save(:validate => false)
u52 = Rsvp.new(:first_name => 'Sunny', :last_name => 'Liu', :confirmation_code =>'MATHLETES')
    u52.save(:validate => false)
u53 = Rsvp.new(:first_name => 'Jennifer', :last_name => 'Owens', :confirmation_code =>'GOBIGRED')
    u53.save(:validate => false)
u54 = Rsvp.new(:first_name => 'Keith', :last_name => 'Eisenmann', :confirmation_code =>'GOBIGRED')
    u54.save(:validate => false)
u55 = Rsvp.new(:first_name => 'Sara', :last_name => 'Chang', :confirmation_code =>'SHARABHERA')
    u55.save(:validate => false)
u56 = Rsvp.new(:first_name => 'Robert', :last_name => 'Chang', :confirmation_code =>'SHARABHERA')
    u56.save(:validate => false)
u57 = Rsvp.new(:first_name => 'Jenny', :last_name => 'Liao', :confirmation_code =>'HUALIEN')
    u57.save(:validate => false)
u59 = Rsvp.new(:first_name => 'Christopher', :last_name => 'Lin', :confirmation_code =>'')
    u59.save(:validate => false)
u60 = Rsvp.new(:first_name => 'Cynthia', :last_name => 'Hsia', :confirmation_code =>'CYNTHIA')
    u60.save(:validate => false)
u61 = Rsvp.new(:first_name => 'Mari', :last_name => 'Tamura', :confirmation_code =>'')
    u61.save(:validate => false)
u62 = Rsvp.new(:first_name => 'Randy', :last_name => 'Tamura', :confirmation_code =>'')
    u62.save(:validate => false)
u63 = Rsvp.new(:first_name => 'Pi-Chin', :last_name => 'Lin', :confirmation_code =>'')
    u63.save(:validate => false)
u64 = Rsvp.new(:first_name => 'Yun-Ching', :last_name => 'Wang', :confirmation_code =>'')
    u64.save(:validate => false)
u65 = Rsvp.new(:first_name => 'Michelle', :last_name => 'Sineff', :confirmation_code =>'SONOMA5115')
    u65.save(:validate => false)
u66 = Rsvp.new(:first_name => 'Sandy', :last_name => 'Sineff', :confirmation_code =>'SONOMA5115')
    u66.save(:validate => false)
u67 = Rsvp.new(:first_name => 'Madison', :last_name => 'Sineff', :confirmation_code =>'SONOMA5115')
    u67.save(:validate => false)
u68 = Rsvp.new(:first_name => 'Alex', :last_name => 'Sineff', :confirmation_code =>'SONOMA5115')
    u68.save(:validate => false)
u69 = Rsvp.new(:first_name => 'Mary', :last_name => 'Chen', :confirmation_code =>'')
    u69.save(:validate => false)
u70 = Rsvp.new(:first_name => 'Thomas', :last_name => 'Chen', :confirmation_code =>'')
    u70.save(:validate => false)
u71 = Rsvp.new(:first_name => 'Emily', :last_name => 'Chen', :confirmation_code =>'JEMILY')
    u71.save(:validate => false)
u72 = Rsvp.new(:first_name => 'Jeff', :last_name => 'Chen', :confirmation_code =>'JEMILY')
    u72.save(:validate => false)
u73 = Rsvp.new(:first_name => 'Tzui', :last_name => 'Lin', :confirmation_code =>'')
    u73.save(:validate => false)
u74 = Rsvp.new(:first_name => 'Henry', :last_name => 'Hsu', :confirmation_code =>'')
    u74.save(:validate => false)
u75 = Rsvp.new(:first_name => 'Nicole', :last_name => 'Azores', :confirmation_code =>'')
    u75.save(:validate => false)
u76 = Rsvp.new(:first_name => 'Steve', :last_name => 'Tung', :confirmation_code =>'')
    u76.save(:validate => false)
u77 = Rsvp.new(:first_name => 'Juan', :last_name => 'Saenz', :confirmation_code =>'')
    u77.save(:validate => false)
u78 = Rsvp.new(:first_name => 'Oriole', :last_name => 'Huang', :confirmation_code =>'')
    u78.save(:validate => false)
u79 = Rsvp.new(:first_name => 'Audrey', :last_name => 'Chang', :confirmation_code =>'')
    u79.save(:validate => false)
u80 = Rsvp.new(:first_name => 'Louis', :last_name => 'Chang', :confirmation_code =>'')
    u80.save(:validate => false)
u81 = Rsvp.new(:first_name => 'Donna', :last_name => 'sai', :confirmation_code =>'')
    u81.save(:validate => false)
u82 = Rsvp.new(:first_name => 'Edison', :last_name => 'Lin', :confirmation_code =>'')
    u82.save(:validate => false)
u83 = Rsvp.new(:first_name => 'Ashley', :last_name => 'Chi', :confirmation_code =>'RILEYROBB')
    u83.save(:validate => false)
u84 = Rsvp.new(:first_name => 'Joe', :last_name => 'DiMaria', :confirmation_code =>'RILEYROBB')
    u84.save(:validate => false)
u85 = Rsvp.new(:first_name => 'Elizabeth', :last_name => 'Lee', :confirmation_code =>'ASTORCOURT')
    u85.save(:validate => false)
u86 = Rsvp.new(:first_name => 'Dave', :last_name => 'Ng', :confirmation_code =>'ASTORCOURT')
    u86.save(:validate => false)
u87 = Rsvp.new(:first_name => 'Michael', :last_name => 'Shing', :confirmation_code =>'')
    u87.save(:validate => false)
u88 = Rsvp.new(:first_name => 'Elsa', :last_name => 'Shing', :confirmation_code =>'')
    u88.save(:validate => false)
u89 = Rsvp.new(:first_name => 'Jennifer', :last_name => 'Lien', :confirmation_code =>'AUSTRALIA')
    u89.save(:validate => false)
u90 = Rsvp.new(:first_name => 'Nick', :last_name => 'Chin', :confirmation_code =>'AUSTRALIA')
    u90.save(:validate => false)
u91 = Rsvp.new(:first_name => 'Debby', :last_name => 'Fu', :confirmation_code =>'')
    u91.save(:validate => false)
u94 = Rsvp.new(:first_name => 'Bryan', :last_name => 'Chen', :confirmation_code =>'HALFDOME')
    u94.save(:validate => false)
u95 = Rsvp.new(:first_name => 'Sandy', :last_name => 'Shieh', :confirmation_code =>'HALFDOME')
    u95.save(:validate => false)
u96 = Rsvp.new(:first_name => 'Jack', :last_name => 'Guo', :confirmation_code =>'')
    u96.save(:validate => false)
u97 = Rsvp.new(:first_name => 'Shi-Yen', :last_name => 'Hsu', :confirmation_code =>'')
    u97.save(:validate => false)
u98 = Rsvp.new(:first_name => 'Serena', :last_name => 'Lee', :confirmation_code =>'')
    u98.save(:validate => false)
u99 = Rsvp.new(:first_name => 'Seggy', :last_name => 'Umboh', :confirmation_code =>'')
    u99.save(:validate => false)
u100 = Rsvp.new(:first_name => 'Ivana', :last_name => 'Chang', :confirmation_code =>'')
    u100.save(:validate => false)
u101 = Rsvp.new(:first_name => 'Ted', :last_name => 'Chang', :confirmation_code =>'')
    u101.save(:validate => false)
u102 = Rsvp.new(:first_name => 'Jesse', :last_name => 'Yu', :confirmation_code =>'')
    u102.save(:validate => false)
u103 = Rsvp.new(:first_name => 'RJ', :last_name => 'Cheng', :confirmation_code =>'')
    u103.save(:validate => false)
  end
end
